name: TrustPlugin
version: '1.0-SNAPSHOT'
main: org.referix.trustPlugin.TrustPlugin
api-version: '1.21'
depend: [LuckPerms]
commands:
  trusts:
    usage: /<command>
    description: add reputation
    permission: trust.reload
  trust:
    usage: /<command>
    description: add reputation
    permission: trust.addreputation
    alias:
      - trust
  safezone:
    usage: /<command>
    description: право виконувати команду для створення власноъ сейв зони
    permission: trust.safezone.create
  untrust:
    usage: /<command>
    description: remove reputation
    permission: trust.removereputation
    alias:
      - untrust
  listrep:
    description: Показує історію змін репутації
    permission: trust.list
    usage: /listrep [all|<гравець>] [сторінка]
  trustaccept:
    description: додати репутацію
    permission: trust.accept
    usage: /listrep [all|<гравець>] [сторінка]
  trustdeny:
    description: відмінити додавання цієї репутації
    permission: trust.deny
    usage: /listrep [all|<гравець>] [сторінка]